### PR TITLE
fix: avoid panics in ParseNode()

### LINKED ISSUE #20: Panic when calling ParseNode with nil arguments
```go
ParseNode(something, nil)
```
will panic, if `something` does not contain a `<base>` tag with an absolute path in `<head>`, which kinda makes sense, but not quite, since microformats can contain absolute paths, in which case the node will be parseable even without any knowledge of the base path.

```go
ParseNode(nil, anything)
```
will panic in any case. I think returning `nil` instead would be perferrable.

### PR DESCRIPTION
**Pull request by nekr0z**
this fixes #20 

`ParseNode(node, nil)` should be able to avoid panic even if `node` does not contain a valid absolute base path in its `<head>`, since there can be usable microformats with absolute paths or no paths.

`ParseNode(nil, base)` should return `nil` instead of panic, because why panic?

### CODE REVIEW

File: microformats_test.go [hunk 1]
```diff
@@ -561,3 +561,20 @@ func Test_GetFirstPropValue(t *testing.T) {
 		}
 	}
 }
+
+func Test_ParseNodeNil(t *testing.T) {
+	tests := map[string]string{
```
Comment (willnorris) [inline microformats_test.go:566]: even though a map does work here, go ahead and use a slice of structs...

``` go
tests := []struct {
    name string
    html string
}{ ... }
```

File: microformats_test.go [hunk 2]
```diff
@@ -561,3 +561,20 @@ func Test_GetFirstPropValue(t *testing.T) {
...
+		"relative": "<html><head><base href=\"./something\"></head></html>",
+		"none":     "<html><head></head></html>", // parseNode(tt) == nil
+	}
+	for name, tt := range tests {
+		t.Run(name, func(t *testing.T) {
+			n, err := parseNode(tt)
+			if err != nil {
+				t.Fatalf("Error parsing HTML: %v", err)
+			}
+			ParseNode(n, nil)
```
Comment (willnorris) [inline microformats_test.go:577]: It's not obvious why we are calling ParseNode here, but not doing anything with the return value.  Maybe add a comment `// ParseNode shouldn't panic` ?

File: microformats.go [hunk 3]
```diff
@@ -118,13 +118,19 @@ func Parse(r io.Reader, baseURL *url.URL) *Data {
 // ParseNode parses the microformats found in doc.  baseURL is the URL this
 // document was retrieved from and is used to resolve any relative URLs.
```
Comment (willnorris) [inline microformats.go:119]: I think it's worth updating the godoc to clarify the behavior when baseURL is nil.  Something like `If baseURL is nil, relative URLs are not expanded.`  If you don't mind, maybe also change "resolve" to "expanded" in that last sentence as well, since we're not actually doing any URL resolution?

**Review by willnorris — CHANGES_REQUESTED** [review]
> because why panic?

Why indeed? :) This looks good to me, just a couple of minor comments below.  Thanks!

File: microformats.go (hunk 3 above)
Comment (nekr0z) [reply microformats.go]: In fact, as long as an absolute base URL is in the document (i.e. `<base href="https://example.com">` we do expand the relative URLs even if `baseURL` is `nil`.

I tried to document this (also in `Parse()` for consistency), but the wording remains clumsy IMO.

**Comment by willnorris** [comment]
awesome, thanks!
